
const uiActionTypes = {
    SHOW_CREATE_USER_FORM: 'SHOW_CREATE_USER_FORM',
    HIDE_CREATE_USER_FORM: 'HIDE_CREATE_USER_FORM',
    SHOW_UPDATE_USER_FORM: 'SHOW_UPDATE_USER_FORM',
    HIDE_UPDATE_USER_FORM: 'HIDE_UPDATE_USER_FORM',
}


export default uiActionTypes;
